package mtss.beans.BO;
// default package
// Generated 14 Feb, 2015 11:57:52 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Intercoaltransfer generated by hbm2java
 */
public class Intercoaltransfer implements java.io.Serializable {

	private int dno;
	private Date dateEntry;
	private Long quantity;
	private String source;
	private String destination;
	private Integer type;

	public Intercoaltransfer() {
	}

	public Intercoaltransfer(int dno) {
		this.dno = dno;
	}

	public Intercoaltransfer(int dno, Date dateEntry, Long quantity,
			String source, String destination, Integer type) {
		this.dno = dno;
		this.dateEntry = dateEntry;
		this.quantity = quantity;
		this.source = source;
		this.destination = destination;
		this.type = type;
	}

	public int getDno() {
		return this.dno;
	}

	public void setDno(int dno) {
		this.dno = dno;
	}

	public Date getDateEntry() {
		return this.dateEntry;
	}

	public void setDateEntry(Date dateEntry) {
		this.dateEntry = dateEntry;
	}

	public Long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
