package mtss.beans.BO;
// default package
// Generated 14 Feb, 2015 11:57:52 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Internalcoaltrans generated by hbm2java
 */
public class Internalcoaltrans implements java.io.Serializable {

	private int activityNo;
	private Gpsinventory gpsinventory;
	private Epcinventory epcinventory;
	private Integer doNo;
	private Long firstWeight;
	private Date firstWeightTime;
	private Long secondWeight;
	private Date secondWeightTime;
	private Long netweight;

	public Internalcoaltrans() {
	}

	public Internalcoaltrans(int activityNo) {
		this.activityNo = activityNo;
	}

	public Internalcoaltrans(int activityNo, Gpsinventory gpsinventory,
			Epcinventory epcinventory, Integer doNo, Long firstWeight,
			Date firstWeightTime, Long secondWeight, Date secondWeightTime,
			Long netweight) {
		this.activityNo = activityNo;
		this.gpsinventory = gpsinventory;
		this.epcinventory = epcinventory;
		this.doNo = doNo;
		this.firstWeight = firstWeight;
		this.firstWeightTime = firstWeightTime;
		this.secondWeight = secondWeight;
		this.secondWeightTime = secondWeightTime;
		this.netweight = netweight;
	}

	public int getActivityNo() {
		return this.activityNo;
	}

	public void setActivityNo(int activityNo) {
		this.activityNo = activityNo;
	}

	public Gpsinventory getGpsinventory() {
		return this.gpsinventory;
	}

	public void setGpsinventory(Gpsinventory gpsinventory) {
		this.gpsinventory = gpsinventory;
	}

	public Epcinventory getEpcinventory() {
		return this.epcinventory;
	}

	public void setEpcinventory(Epcinventory epcinventory) {
		this.epcinventory = epcinventory;
	}

	public Integer getDoNo() {
		return this.doNo;
	}

	public void setDoNo(Integer doNo) {
		this.doNo = doNo;
	}

	public Long getFirstWeight() {
		return this.firstWeight;
	}

	public void setFirstWeight(Long firstWeight) {
		this.firstWeight = firstWeight;
	}

	public Date getFirstWeightTime() {
		return this.firstWeightTime;
	}

	public void setFirstWeightTime(Date firstWeightTime) {
		this.firstWeightTime = firstWeightTime;
	}

	public Long getSecondWeight() {
		return this.secondWeight;
	}

	public void setSecondWeight(Long secondWeight) {
		this.secondWeight = secondWeight;
	}

	public Date getSecondWeightTime() {
		return this.secondWeightTime;
	}

	public void setSecondWeightTime(Date secondWeightTime) {
		this.secondWeightTime = secondWeightTime;
	}

	public Long getNetweight() {
		return this.netweight;
	}

	public void setNetweight(Long netweight) {
		this.netweight = netweight;
	}

}
