package mtss.beans.BO;
// default package
// Generated 14 Feb, 2015 11:57:52 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Othergood generated by hbm2java
 */
public class Othergood implements java.io.Serializable {

	private Integer otherActivityNo;
	private Date dateTimeIssue;
	private Long weight1;
	private String quantityType;
	private Long weight2;
	private Long netWeight;
	private Date dateReturn;
	private String challenNo;

	public Othergood() {
	}

	public Othergood(Date dateTimeIssue, Long weight1, String quantityType,
			Long weight2, Long netWeight, Date dateReturn, String challenNo) {
		this.dateTimeIssue = dateTimeIssue;
		this.weight1 = weight1;
		this.quantityType = quantityType;
		this.weight2 = weight2;
		this.netWeight = netWeight;
		this.dateReturn = dateReturn;
		this.challenNo = challenNo;
	}

	public Integer getOtherActivityNo() {
		return this.otherActivityNo;
	}

	public void setOtherActivityNo(Integer otherActivityNo) {
		this.otherActivityNo = otherActivityNo;
	}

	public Date getDateTimeIssue() {
		return this.dateTimeIssue;
	}

	public void setDateTimeIssue(Date dateTimeIssue) {
		this.dateTimeIssue = dateTimeIssue;
	}

	public Long getWeight1() {
		return this.weight1;
	}

	public void setWeight1(Long weight1) {
		this.weight1 = weight1;
	}

	public String getQuantityType() {
		return this.quantityType;
	}

	public void setQuantityType(String quantityType) {
		this.quantityType = quantityType;
	}

	public Long getWeight2() {
		return this.weight2;
	}

	public void setWeight2(Long weight2) {
		this.weight2 = weight2;
	}

	public Long getNetWeight() {
		return this.netWeight;
	}

	public void setNetWeight(Long netWeight) {
		this.netWeight = netWeight;
	}

	public Date getDateReturn() {
		return this.dateReturn;
	}

	public void setDateReturn(Date dateReturn) {
		this.dateReturn = dateReturn;
	}

	public String getChallenNo() {
		return this.challenNo;
	}

	public void setChallenNo(String challenNo) {
		this.challenNo = challenNo;
	}

}
