package mtss.beans.BO;
// default package
// Generated 14 Feb, 2015 11:57:52 AM by Hibernate Tools 3.4.0.CR1

/**
 * Productionvechdetail generated by hbm2java
 */
public class Productionvechdetail implements java.io.Serializable {

	private Integer id;
	private Integer epcno;
	private String vechNo;
	private Long tareWeight;

	public Productionvechdetail() {
	}

	public Productionvechdetail(Integer epcno, String vechNo, Long tareWeight) {
		this.epcno = epcno;
		this.vechNo = vechNo;
		this.tareWeight = tareWeight;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getEpcno() {
		return this.epcno;
	}

	public void setEpcno(Integer epcno) {
		this.epcno = epcno;
	}

	public String getVechNo() {
		return this.vechNo;
	}

	public void setVechNo(String vechNo) {
		this.vechNo = vechNo;
	}

	public Long getTareWeight() {
		return this.tareWeight;
	}

	public void setTareWeight(Long tareWeight) {
		this.tareWeight = tareWeight;
	}

}
