package mtss.beans.BO;
// default package
// Generated 14 Feb, 2015 11:57:52 AM by Hibernate Tools 3.4.0.CR1

/**
 * Taxnames generated by hbm2java
 */
public class Taxnames implements java.io.Serializable {

	private Integer id;
	private String taxName;

	public Taxnames() {
	}

	public Taxnames(String taxName) {
		this.taxName = taxName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTaxName() {
		return this.taxName;
	}

	public void setTaxName(String taxName) {
		this.taxName = taxName;
	}

}
