package mtss.beans.BO;
// default package
// Generated 14 Feb, 2015 11:57:52 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Useractivity generated by hbm2java
 */
public class Useractivity implements java.io.Serializable {

	private int activityId;
	private Loginuser loginuser;
	private Date loginDate;
	private Date logoutDate;

	public Useractivity() {
	}

	public Useractivity(int activityId) {
		this.activityId = activityId;
	}

	public Useractivity(int activityId, Loginuser loginuser, Date loginDate,
			Date logoutDate) {
		this.activityId = activityId;
		this.loginuser = loginuser;
		this.loginDate = loginDate;
		this.logoutDate = logoutDate;
	}

	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	public Loginuser getLoginuser() {
		return this.loginuser;
	}

	public void setLoginuser(Loginuser loginuser) {
		this.loginuser = loginuser;
	}

	public Date getLoginDate() {
		return this.loginDate;
	}

	public void setLoginDate(Date loginDate) {
		this.loginDate = loginDate;
	}

	public Date getLogoutDate() {
		return this.logoutDate;
	}

	public void setLogoutDate(Date logoutDate) {
		this.logoutDate = logoutDate;
	}

}
